"use client";

import { Check, GitBranch, ShieldCheck, Workflow } from "lucide-react";
import type { Optimization } from "@/lib/contracts";

const money = (value: number) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
const signalNames = { value: "Value", evidence: "Evidence coverage", road_trip: "Road-trip heuristic", model_fit: "Model-fit heuristic", mileage_year_battery: "Mileage / year / battery" };

export default function DealIntelligence({ optimization }: { optimization: Omit<Optimization, "job_token"> }) {
  const { intelligence, simulation, plans } = optimization;
  if (!intelligence && !simulation) return null;
  const title = (id: string) => plans.find(plan => plan.listing_id === id)?.title || id;
  return <div className="intelligence-stack">
    {intelligence && <section className="intelligence-panel"><div className="section-line"><h2><ShieldCheck size={19}/>Intelligence layer</h2><a className="text-button" href={`https://github.com/benikigai/JEVgotiator/commit/${intelligence.source_commit}`} target="_blank" rel="noreferrer"><GitBranch size={13}/>Dara’s scoring logic</a></div><p className="intelligence-method">Selected cars are compared using Dara’s weighted scoring rules. Jev’s shortlist is preserved.</p><div className="intelligence-candidates">{intelligence.candidates.map(candidate => <article className="intelligence-candidate" key={candidate.listing_id}><div className="intelligence-candidate-top"><span className="number-chip">{candidate.rank}</span><h3>{title(candidate.listing_id)}</h3><strong>{candidate.score}<small>/ 100</small></strong></div><div className="intelligence-signals">{Object.entries(candidate.signals).map(([name, score]) => <div key={name}><span>{signalNames[name as keyof typeof signalNames]}</span><div><i style={{ width: `${Math.max(0, Math.min(100, score))}%` }}/></div><strong>{Math.round(score)}</strong></div>)}</div><details><summary>Evidence gaps and assumptions</summary><ul>{candidate.unknowns.map((unknown, index) => <li key={index}>{unknown}</li>)}</ul></details></article>)}</div><details className="intelligence-assumptions"><summary>Inspect the scoring method</summary><p>{intelligence.method}</p><ul>{intelligence.assumptions.map((assumption, index) => <li key={index}>{assumption}</li>)}</ul></details></section>}
    {simulation && <section className="intelligence-panel scenario-panel"><div className="section-line"><h2><Workflow size={19}/>Action layer</h2><span className="scenario-badge">SYNTHETIC NEGOTIATION SIMULATION</span></div><p className="intelligence-method">A worked negotiation scenario for the selected demo cars. Prices below are assumptions, not seller quotes.</p><div className="scenario-table-wrap"><table className="scenario-table"><thead><tr><th>Selected car</th><th>Asking</th><th>Opening offer</th><th>Assumed counter</th><th>Assumed agreement</th></tr></thead><tbody>{simulation.candidates.map(candidate => <tr key={candidate.listing_id}><td><strong>{title(candidate.listing_id)}</strong><small>{money(candidate.simulated_savings)} hypothetical savings</small></td><td>{money(candidate.asking_price)}</td><td>{money(candidate.opening_offer)}</td><td>{money(candidate.simulated_counter)}</td><td><strong>{money(candidate.simulated_agreed_price)}</strong></td></tr>)}</tbody></table></div><div className="scenario-actions">{simulation.actions.map((action, index) => <div className={`scenario-action ${action.state}`} key={index}><span>{action.state === "done" ? <Check size={13}/> : index + 1}</span><div><strong>{action.label}</strong><p>{action.detail}</p></div></div>)}</div><details className="intelligence-assumptions"><summary>Scenario assumptions and comparison</summary>{simulation.assumptions.map((assumption, index) => <p key={index}>{assumption}</p>)}{simulation.candidates.map(candidate => <p key={candidate.listing_id}><strong>{title(candidate.listing_id)}:</strong> {candidate.recommendation}</p>)}</details><p className="scenario-disclaimer">{simulation.disclaimer}</p></section>}
  </div>;
}
