"use client";

import { useState } from "react";
import { ArrowDown, ArrowLeft, Check, Code2, Database, Zap } from "lucide-react";
import type { SearchResult } from "@/lib/contracts";

const percent = (value: number) => `${(value * 100).toFixed(1)}%`;

export default function DecisionTrace({ result, onBack }: { result: SearchResult | null; onBack: () => void }) {
  const [activeId, setActiveId] = useState("");
  const trace = result?.ranking.trace;
  if (!result || !trace) return <div className="empty-state"><Zap size={32}/><h2>See exactly where Jev contributes.</h2><p>Run a search to record its questions, input evidence, returned scores, and the arithmetic behind the shortlist.</p><button className="primary" onClick={onBack}>Run a search</button></div>;
  const selected = trace.candidates.find(candidate => candidate.listing_id === activeId) || trace.candidates.find(candidate => candidate.listing_id === result.results[0]?.listing.id) || trace.candidates[0];
  const composition = trace.composition.find(row => row.listing_id === selected?.listing_id);
  const selectedQuestions = trace.questions.filter(question => question.listing_id === selected?.listing_id);
  const matched = new Set(result.results.map(row => row.listing.id));
  function download() {
    const artifact = { search_id: result!.session_id, created_at: result!.created_at, brief: result!.brief, counts: result!.counts, catalog: result!.catalog, ranking: result!.ranking };
    const url = URL.createObjectURL(new Blob([JSON.stringify(artifact, null, 2)], { type: "application/json" }));
    const link = document.createElement("a"); link.href = url; link.download = "jevgotiator-decision-trace.json"; link.click(); URL.revokeObjectURL(url);
  }
  return <>
    <section className="page-heading compact"><div><span className="eyebrow">THE DECISION RECORD</span><h1>Here’s what Jev did.</h1><p>Recorded inputs, returned scores, and the calculation behind this search.</p></div><button className="secondary" onClick={onBack}><ArrowLeft size={16}/>Results</button></section>
    <div className="trace-stages">
      <section><Database size={20}/><span className="eyebrow">01 · OUR CODE</span><h2>{result.counts.total.toLocaleString()} → {result.counts.eligible}</h2><strong>Apply hard constraints</strong><p>Location, availability, budget, model, year, mileage, and required history.</p></section>
      <section className="trace-stage-jev"><Zap size={20}/><span className="eyebrow">02 · JEV</span><h2>{trace.answers.filter(answer => answer.used).length} scores</h2><strong>Evaluate supplied evidence</strong><p>{result.counts.candidates} candidates. Buyer fit and maintenance questions answered with typed 0–1 scores.</p></section>
      <section><Code2 size={20}/><span className="eyebrow">03 · OUR CODE</span><h2>{result.counts.shown} matches</h2><strong>Calculate and sort</strong><p>Explicit weights combine the returned scores. The buyer chooses one to three cars.</p></section>
    </div>
    <div className="trace-meta"><span className="data-badge">{trace.outcome === "scored" ? "LIVE RESPONSE RECORDED" : trace.outcome === "failed" ? "SCORING FAILED" : "NOT REQUESTED"}</span><span>{trace.returned_model || trace.requested_model}</span><span>{result.ranking.input_tokens.toLocaleString()} input tokens</span><span>{(result.ranking.latency_ms / 1000).toFixed(2)}s</span><span>${result.ranking.estimated_cost_usd.toFixed(6)} estimated</span><button className="text-button" onClick={download}><ArrowDown size={14}/>Export trace</button></div>
    <div className="notice">{trace.note} {result.catalog.mode === "synthetic" ? "The inventory is synthetic; the recorded Jev response is live when marked above." : "Listing evidence remains a source claim."}</div>
    <section className="trace-section"><div className="section-line"><h2>Buyer request and confirmed constraints</h2><span className="quiet">{new Date(result.created_at).toLocaleString()}</span></div><blockquote>{trace.buyer_request}</blockquote><div className="trace-constraints"><span>Tesla{result.brief.model ? ` · ${result.brief.model}` : " · Any model"}</span><span>San Francisco</span><span>Budget ${result.brief.budget.toLocaleString()} · {result.brief.budget_basis === "out_the_door" ? "final total provisional" : "asking price"}</span>{result.brief.max_mileage !== null && <span>≤ {result.brief.max_mileage.toLocaleString()} miles</span>}{result.brief.min_year !== null && <span>{result.brief.min_year} or newer</span>}{result.brief.color && <span>{result.brief.color}</span>}{result.brief.clean_title && <span>Clean title reported</span>}{result.brief.no_reported_accidents && <span>No accidents reported</span>}</div><p className="trace-description">{trace.hard_filter_role}</p>{result.catalog.warnings.map((warning, index) => <p className="trace-description" key={index}>{warning}</p>)}</section>
    <section className="trace-section"><div className="section-line"><h2>Score composition</h2><span className="quiet">{trace.composition.length} ranked candidates</span></div><p className="trace-description">{trace.algorithm}</p>{trace.composition.length ? <div className="trace-table-wrap"><table className="trace-table"><thead><tr><th>Rank</th><th>Candidate</th><th>Jev buyer fit</th><th>Jev maintenance</th><th>Code factor</th><th>Final score</th></tr></thead><tbody>{trace.composition.map(row => { const candidate = trace.candidates.find(item => item.listing_id === row.listing_id); const fit = row.factors.find(factor => factor.name === "Buyer fit"); const maintenance = row.factors.find(factor => factor.name === "Maintenance evidence"); const coded = row.factors.find(factor => factor.source === "code"); return <tr key={row.listing_id} className={selected?.listing_id === row.listing_id ? "trace-row-selected" : ""}><td>{row.rank}{matched.has(row.listing_id) && <Check size={12}/>}</td><td><button onClick={() => setActiveId(row.listing_id)}>{candidate?.label || row.listing_id}<small>{row.listing_id}</small></button></td><td>{fit ? percent(fit.score) : "Unavailable"}</td><td>{maintenance ? percent(maintenance.score) : "Not supplied"}</td><td>{coded ? `${percent(coded.score)} ${coded.name}` : "None"}</td><td><strong>{percent(row.final_score)}</strong></td></tr>; })}</tbody></table></div> : <div className="notice">No accepted Jev scores. No AI ranking was fabricated.</div>}</section>
    {selected && <section className="trace-section"><div className="section-line"><h2>Inspect one candidate</h2><select aria-label="Trace candidate" value={selected.listing_id} onChange={event => setActiveId(event.target.value)}>{trace.candidates.map(candidate => <option key={candidate.listing_id} value={candidate.listing_id}>{candidate.label} · {candidate.listing_id}</option>)}</select></div><span className="eyebrow">{selected.state_path}</span><h3 className="trace-candidate-title">{selected.label}</h3><details className="trace-json"><summary>Exact listing evidence sent to Jev</summary><pre>{JSON.stringify(selected.model_context, null, 2)}</pre></details>{selectedQuestions.map(question => { const answer = trace.answers.find(item => item.question_id === question.question_id); return <div className="trace-question" key={question.question_id}><div className="section-line"><h3>{question.factor}</h3><span className="data-badge">{answer?.used && answer.noul !== null ? `Jev returned ${answer.noul.toFixed(4)}` : "No accepted score"}</span></div><code>{question.question_id} · {question.type}</code><p>{question.instructions}</p><div className="trace-criteria"><div><strong>1.0 means</strong><p>{question.criteria.true}</p></div><div><strong>0.0 means</strong><p>{question.criteria.false}</p></div></div></div>; })}{composition && <div className="trace-formula"><span className="eyebrow">FINAL SCORE CALCULATION</span><p>{composition.factors.map(factor => `${factor.score.toFixed(4)} × ${factor.normalized_weight.toFixed(4)}`).join(" + ")} = <strong>{composition.final_score.toFixed(4)}</strong></p>{composition.factors.map(factor => <small key={factor.name}>{factor.name}: {percent(factor.normalized_weight)} weight · {factor.source === "jev" ? "Jev response" : "calculated in code"}</small>)}</div>}</section>}
  </>;
}
